### PR TITLE
Travis already updates composer itself

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by nunomaduro** [comment]
TIL. 👌🏻

**Comment by szepeviktor** [comment]
You could have a base repo with all tools and default configs.

**Comment by nunomaduro** [comment]
That could be a good idea!

**Comment by carusogabriel** [comment]
@szepeviktor Do you have any documentation of proof about this?

I'd like to replicate it to some repos as well, but I'd need some proof.

**Comment by olivernybroe** [comment]
@carusogabriel 

> Note that we update composer every time we update the PHP build environment, which is every 30-60 days. Because composer has a time-based update warning, you may see messages such as this, which may be safely ignored:

https://docs.travis-ci.com/user/languages/php#installing-composer-packages

**Comment by szepeviktor** [comment]
@olivernybroe This update mechanism is not in the OS image but a step in CI run.

image

**Pull request merged**
